name: bit_magnet
description: Axess Hackathon 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_login: ^1.0.14
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  searchable_dropdown:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

